### ISSUE TITLE
Update to luajwtjitsi 3.0.0

### ISSUE THREAD

**Issue by rkorn86** [matrix-org/prosody-mod-auth-matrix-user-verification#14]
Jitsi/Prosody updated their Docker Image to Lua 5.4 and therefore they needed to update `luajwtjitsi` to 3.0.0. Unfortunately `mod_auth_matrix_user_verification.lua` is not compatible with `luajwtjitsi` 3.0.0 (error on Line #L178 - `jwt.decode` is `nil`).
Please provide an updated script, which is compatible with `luajwtjitsi` 3.0.0.

Thank you so far.

**Comment by chagai95** [comment]
Also got this and rolled back to 7001 of prosody to avoid this. Would be better to use the newest though 🙈

**Comment by benbz** [comment]
This should have been fixed by #19 and releases as 1.8.0. Also #18 for use with newer Jitsi versions too.

Feel free to reopen if you're still having issues

**Comment by chagai95** [comment]
I think the jitsi prosody also has to add this to their docker build, how is the process to inform them about this?

**Comment by benbz** [comment]
> I think the jitsi prosody also has to add this to their docker build, how is the process to inform them about this?

https://github.com/jitsi/docker-jitsi-meet/pull/1403
